# Generated by Django 5.0.14 on 2026-02-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_add_billing_interval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershiptier',
            options={'ordering': ['display_order'], 'verbose_name': 'membership tier', 'verbose_name_plural': 'membership tiers'},
        ),
        migrations.AlterModelOptions(
            name='usermembership',
            options={'verbose_name': 'user membership', 'verbose_name_plural': 'user memberships'},
        ),
    ]
