# Generated by Django 5.0.14 on 2026-02-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0003_generatedcontent_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcontent',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Whether this content is marked as favorite'),
        ),
        migrations.AlterField(
            model_name='generatedcontent',
            name='content_type',
            field=models.CharField(choices=[('lesson_starter', 'Lesson Starter'), ('learning_objectives', 'Learning Objectives'), ('quiz', 'Quiz'), ('other', 'Other')], max_length=50),
        ),
    ]
